import { Router } from 'express';
import { z } from 'zod';
import { db } from '../database.js';
import { requireAuth, requireRole } from '../auth.js';
export const teacherAdminRouter=Router();
teacherAdminRouter.use(requireAuth,requireRole('teacher','admin'));
// Every teacher has the same administration capabilities as an administrator.
function canManageClass(req,id){return !!db.prepare('SELECT 1 FROM classes WHERE id=?').get(id);}
teacherAdminRouter.get('/overview',(req,res)=>{const classes=db.prepare(`SELECT c.id,c.name,c.code,c.teacher_id,u.username teacher_name,COUNT(cm.user_id) member_count FROM classes c JOIN users u ON u.id=c.teacher_id LEFT JOIN class_members cm ON cm.class_id=c.id GROUP BY c.id ORDER BY c.name`).all();const students=db.prepare(`SELECT u.id,u.username,u.email,u.role,u.xp,u.level,u.coins,COUNT(DISTINCT cm.class_id) class_count FROM users u LEFT JOIN class_members cm ON cm.user_id=u.id WHERE u.role='student' GROUP BY u.id ORDER BY u.username COLLATE NOCASE`).all();res.json({classes,students});});
teacherAdminRouter.get('/classes/:classId/students',(req,res)=>{const id=Number(req.params.classId);if(!canManageClass(req,id))return res.status(403).json({error:'Classe inaccessible'});res.json({students:db.prepare(`SELECT u.id,u.username,u.email,u.xp,u.level,u.coins,cm.joined_at FROM class_members cm JOIN users u ON u.id=cm.user_id WHERE cm.class_id=? AND u.role='student' ORDER BY u.username COLLATE NOCASE`).all(id)});});
teacherAdminRouter.post('/students/move',(req,res)=>{const p=z.object({userId:z.coerce.number().int().positive(),fromClassId:z.coerce.number().int().positive().nullable().optional(),toClassId:z.coerce.number().int().positive().nullable().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Données invalides'});const{userId,fromClassId,toClassId}=p.data;if(!db.prepare("SELECT 1 FROM users WHERE id=? AND role='student'").get(userId))return res.status(404).json({error:'Élève introuvable'});if(fromClassId&&!canManageClass(req,fromClassId))return res.status(403).json({error:'Classe source inaccessible'});if(toClassId&&!canManageClass(req,toClassId))return res.status(403).json({error:'Classe destination inaccessible'});db.transaction(()=>{db.prepare('DELETE FROM class_members WHERE user_id=?').run(userId);if(toClassId)db.prepare('INSERT OR IGNORE INTO class_members(class_id,user_id) VALUES(?,?)').run(toClassId,userId);})();res.json({ok:true,userId,classId:toClassId||null});});
teacherAdminRouter.post('/classes',(req,res)=>{const p=z.object({name:z.string().trim().min(2).max(80),teacherId:z.coerce.number().int().positive().optional()}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Nom de classe invalide'});let code;do{code=Math.random().toString(36).slice(2,8).toUpperCase();}while(db.prepare('SELECT 1 FROM classes WHERE code=?').get(code));const teacherId=p.data.teacherId||req.user.id;if(!db.prepare("SELECT id FROM users WHERE id=? AND role IN ('teacher','admin')").get(teacherId))return res.status(400).json({error:'Professeur invalide'});const r=db.prepare('INSERT INTO classes(teacher_id,name,code) VALUES(?,?,?)').run(teacherId,p.data.name,code);res.status(201).json({id:r.lastInsertRowid,name:p.data.name,code});});
function svgClean(input){const svg=String(input||'').trim();if(!svg||svg.length>200000)return '';if(!/<svg(?:\s|>)/i.test(svg))throw new Error('INVALID_SVG');if(/<(?:script|foreignObject|iframe|object|embed|audio|video|link|meta)\b/i.test(svg)||/\bon[a-z]+\s*=|javascript\s*:|data\s*:\s*text\/html|<\?xml-stylesheet/i.test(svg)||/\b(?:href|xlink:href)\s*=\s*["']\s*(?:https?:|\/\/|javascript:|data:)/i.test(svg))throw new Error('UNSAFE_SVG');return svg;}
const itemSchema=z.object({name:z.string().trim().min(2).max(80).optional(),category:z.enum(['character','outfit','style','background']).optional(),style:z.string().trim().min(1).max(64).optional(),price:z.coerce.number().int().min(0).max(100000).optional(),description:z.string().max(240).optional(),icon:z.string().max(8).optional(),active:z.coerce.boolean().optional(),svgContent:z.string().max(200000).optional(),anchor:z.enum(['center','head','face','body','feet','back']).optional(),posX:z.coerce.number().min(0).max(100).optional(),posY:z.coerce.number().min(0).max(100).optional(),scale:z.coerce.number().min(5).max(300).optional(),rotation:z.coerce.number().min(-180).max(180).optional()});
teacherAdminRouter.post('/catalog/items',(req,res)=>{const p=z.object({slug:z.string().trim().regex(/^[a-z0-9-]+$/).max(64),name:z.string().trim().min(2).max(80),category:z.enum(['character','outfit','style','background']).default('style'),style:z.string().trim().min(1).max(64).default('toon-head'),price:z.coerce.number().int().min(0).max(100000),description:z.string().max(240).default(''),icon:z.string().max(8).default('✨'),svgContent:z.string().max(200000).default(''),anchor:z.enum(['center','head','face','body','feet','back']).default('center'),posX:z.coerce.number().min(0).max(100).default(50),posY:z.coerce.number().min(0).max(100).default(50),scale:z.coerce.number().min(5).max(300).default(100),rotation:z.coerce.number().min(-180).max(180).default(0)}).safeParse(req.body);if(!p.success)return res.status(400).json({error:'Élément invalide',details:p.error.flatten()});let svg;try{svg=svgClean(p.data.svgContent||'')}catch(e){return res.status(400).json({error:e.message==='UNSAFE_SVG'?'SVG refusé pour raisons de sécurité':'Le contenu doit être un SVG valide'});}try{const r=db.prepare('INSERT INTO avatar_items(slug,name,category,style,price,description,icon,svg_content,creator_id,anchor,pos_x,pos_y,scale,rotation) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(p.data.slug,p.data.name,p.data.category,p.data.style,p.data.price,p.data.description,p.data.icon,svg,req.user.id,p.data.anchor,p.data.posX,p.data.posY,p.data.scale,p.data.rotation);res.status(201).json({ok:true,id:r.lastInsertRowid,slug:p.data.slug});}catch(e){if(String(e.message).includes('UNIQUE'))return res.status(409).json({error:'Ce slug existe déjà'});console.error(e);res.status(500).json({error:'Création impossible'});}});
teacherAdminRouter.patch('/catalog/items/:id',(req,res)=>{const id=Number(req.params.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Élément invalide'});const p=itemSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'Données invalides',details:p.error.flatten()});const cur=db.prepare('SELECT * FROM avatar_items WHERE id=?').get(id);if(!cur)return res.status(404).json({error:'Élément introuvable'});let svg;try{svg=p.data.svgContent===undefined?cur.svg_content:svgClean(p.data.svgContent)}catch(e){return res.status(400).json({error:e.message==='UNSAFE_SVG'?'SVG refusé pour raisons de sécurité':'SVG invalide'});}const n={name:p.data.name??cur.name,category:p.data.category??cur.category,style:p.data.style??cur.style,price:p.data.price??cur.price,description:p.data.description??cur.description,icon:p.data.icon??cur.icon,active:p.data.active===undefined?cur.active:(p.data.active?1:0),svg,anchor:p.data.anchor??cur.anchor,posX:p.data.posX??cur.pos_x,posY:p.data.posY??cur.pos_y,scale:p.data.scale??cur.scale,rotation:p.data.rotation??cur.rotation};db.prepare('UPDATE avatar_items SET name=?,category=?,style=?,price=?,description=?,icon=?,active=?,svg_content=?,anchor=?,pos_x=?,pos_y=?,scale=?,rotation=? WHERE id=?').run(n.name,n.category,n.style,n.price,n.description,n.icon,n.active,n.svg,n.anchor,n.posX,n.posY,n.scale,n.rotation,id);res.json({ok:true});});
teacherAdminRouter.get('/catalog',(_req,res)=>{res.json({items:db.prepare("SELECT id,slug,name,category,style,price,description,icon,active,creator_id,CASE WHEN svg_content<>'' THEN 1 ELSE 0 END has_svg,anchor,pos_x posX,pos_y posY,scale,rotation FROM avatar_items ORDER BY category,price,id").all()});});
