// Data-driven Karhoot avatar catalog.
// v1: only Toon Head. Add future DiceBear styles or Karhoot-owned SVG items here.
export const AVATAR_CATALOG = [
  ['toon-head', 'Toon Head', 'character', 'toon-head', 100, 'Personnage cartoon de base Karhoot', '🎨'],
  ['toon-beard-chin', 'Barbe menton', 'style', 'toon-head', 40, 'Barbe Toon Head', '🧔', 'beardVariant', 'chin'],
  ['toon-beard-chin-moustache', 'Barbe + moustache', 'style', 'toon-head', 60, 'Barbe avec moustache', '🧔', 'beardVariant', 'chinMoustache'],
  ['toon-beard-full', 'Barbe complète', 'style', 'toon-head', 80, 'Barbe complète', '🧔', 'beardVariant', 'fullBeard'],
  ['toon-beard-long', 'Longue barbe', 'style', 'toon-head', 100, 'Longue barbe', '🧔', 'beardVariant', 'longBeard'],
  ['toon-beard-twirl', 'Moustache royale', 'style', 'toon-head', 120, 'Moustache torsadée', '🥸', 'beardVariant', 'moustacheTwirl'],
  ['toon-clothes-dress', 'Robe', 'style', 'toon-head', 100, 'Robe Toon Head', '👗', 'clothesVariant', 'dress'],
  ['toon-clothes-jacket', 'Veste ouverte', 'style', 'toon-head', 100, 'Veste ouverte', '🧥', 'clothesVariant', 'openJacket'],
  ['toon-clothes-shirt', 'Chemise', 'style', 'toon-head', 80, 'Chemise', '👔', 'clothesVariant', 'shirt'],
  ['toon-clothes-tshirt', 'T-shirt', 'style', 'toon-head', 60, 'T-shirt', '👕', 'clothesVariant', 'tShirt'],
  ['toon-clothes-turtleneck', 'Col roulé', 'style', 'toon-head', 90, 'Pull col roulé', '🧶', 'clothesVariant', 'turtleNeck'],
  ['toon-eyebrows-angry', 'Sourcils énervés', 'style', 'toon-head', 35, 'Expression énervée', '😠', 'eyebrowsVariant', 'angry'],
  ['toon-eyebrows-happy', 'Sourcils joyeux', 'style', 'toon-head', 35, 'Expression joyeuse', '😊', 'eyebrowsVariant', 'happy'],
  ['toon-eyebrows-neutral', 'Sourcils neutres', 'style', 'toon-head', 25, 'Expression neutre', '😐', 'eyebrowsVariant', 'neutral'],
  ['toon-eyebrows-raised', 'Sourcils levés', 'style', 'toon-head', 35, 'Sourcils levés', '🤨', 'eyebrowsVariant', 'raised'],
  ['toon-eyebrows-sad', 'Sourcils tristes', 'style', 'toon-head', 35, 'Sourcils tristes', '😢', 'eyebrowsVariant', 'sad'],
  ['toon-eyes-bow', 'Yeux Bow', 'style', 'toon-head', 40, 'Yeux stylisés', '👀', 'eyesVariant', 'bow'],
  ['toon-eyes-happy', 'Yeux joyeux', 'style', 'toon-head', 40, 'Yeux joyeux', '😊', 'eyesVariant', 'happy'],
  ['toon-eyes-humble', 'Yeux doux', 'style', 'toon-head', 40, 'Yeux doux', '🥹', 'eyesVariant', 'humble'],
  ['toon-eyes-wide', 'Grands yeux', 'style', 'toon-head', 45, 'Yeux grands ouverts', '👁️', 'eyesVariant', 'wide'],
  ['toon-eyes-wink', 'Clin d’œil', 'style', 'toon-head', 60, 'Clin d’œil', '😉', 'eyesVariant', 'wink'],
  ['toon-hair-bun', 'Chignon', 'style', 'toon-head', 70, 'Coiffure chignon', '💇', 'hairVariant', 'bun'],
  ['toon-hair-side', 'Mèche sur le côté', 'style', 'toon-head', 70, 'Coiffure latérale', '💇', 'hairVariant', 'sideComed'],
  ['toon-hair-spiky', 'Cheveux hérissés', 'style', 'toon-head', 80, 'Coiffure hérissée', '⚡', 'hairVariant', 'spiky'],
  ['toon-hair-undercut', 'Undercut', 'style', 'toon-head', 90, 'Coiffure undercut', '💈', 'hairVariant', 'undercut'],
  ['toon-head-shape', 'Tête Toon', 'style', 'toon-head', 25, 'Forme de tête Toon Head', '🙂', 'headVariant', 'head'],
  ['toon-mouth-agape', 'Bouche ouverte', 'style', 'toon-head', 40, 'Bouche ouverte', '😮', 'mouthVariant', 'agape'],
  ['toon-mouth-angry', 'Bouche énervée', 'style', 'toon-head', 40, 'Bouche énervée', '😠', 'mouthVariant', 'angry'],
  ['toon-mouth-laugh', 'Rire', 'style', 'toon-head', 45, 'Expression de rire', '😂', 'mouthVariant', 'laugh'],
  ['toon-mouth-sad', 'Bouche triste', 'style', 'toon-head', 40, 'Expression triste', '🙁', 'mouthVariant', 'sad'],
  ['toon-mouth-smile', 'Sourire', 'style', 'toon-head', 30, 'Sourire', '😁', 'mouthVariant', 'smile'],
  ['toon-rear-long-straight', 'Cheveux longs lisses', 'style', 'toon-head', 90, 'Cheveux longs', '💇‍♀️', 'rearHairVariant', 'longStraight'],
  ['toon-rear-long-wavy', 'Cheveux longs ondulés', 'style', 'toon-head', 100, 'Cheveux ondulés', '💇‍♀️', 'rearHairVariant', 'longWavy'],
  ['toon-rear-neck-high', 'Cheveux nuque haute', 'style', 'toon-head', 80, 'Coiffure arrière', '💇', 'rearHairVariant', 'neckHigh'],
  ['toon-rear-shoulder-high', 'Cheveux épaules', 'style', 'toon-head', 100, 'Cheveux jusqu’aux épaules', '💇‍♀️', 'rearHairVariant', 'shoulderHigh'],
  ['toon-clothes-black', 'Vêtements noir', 'style', 'toon-head', 50, 'Couleur de vêtements noire', '⚫', 'clothesColor', '151613'],
  ['toon-clothes-blue', 'Vêtements bleu', 'style', 'toon-head', 50, 'Couleur de vêtements bleue', '🔵', 'clothesColor', '0b3286'],
  ['toon-clothes-grey', 'Vêtements gris', 'style', 'toon-head', 50, 'Couleur de vêtements grise', '⚙️', 'clothesColor', '545454'],
  ['toon-clothes-green', 'Vêtements vert', 'style', 'toon-head', 50, 'Couleur de vêtements verte', '🟢', 'clothesColor', '147f3c'],
  ['toon-clothes-orange', 'Vêtements orange', 'style', 'toon-head', 50, 'Couleur de vêtements orange', '🟠', 'clothesColor', 'f97316'],
  ['toon-clothes-pink', 'Vêtements rose', 'style', 'toon-head', 50, 'Couleur de vêtements rose', '🩷', 'clothesColor', 'ec4899'],
  ['toon-clothes-purple', 'Vêtements violet', 'style', 'toon-head', 60, 'Couleur Karhoot violette', '🟣', 'clothesColor', '731ac3'],
  ['toon-clothes-red', 'Vêtements rouge', 'style', 'toon-head', 50, 'Couleur de vêtements rouge', '🔴', 'clothesColor', 'b11f1f'],
  ['toon-clothes-white', 'Vêtements blanc', 'style', 'toon-head', 50, 'Couleur de vêtements blanche', '⚪', 'clothesColor', 'e8e9e6'],
  ['toon-clothes-gold', 'Vêtements or', 'style', 'toon-head', 100, 'Couleur dorée premium', '🟡', 'clothesColor', 'eab308'],
  ['toon-hair-brown', 'Cheveux bruns', 'style', 'toon-head', 40, 'Couleur de cheveux brune', '🟤', 'hairColor', '2c1b18'],
  ['toon-hair-blond', 'Cheveux blonds', 'style', 'toon-head', 40, 'Couleur blonde', '🟡', 'hairColor', 'd6b370'],
  ['toon-hair-chestnut', 'Cheveux châtain', 'style', 'toon-head', 40, 'Couleur châtain', '🟤', 'hairColor', '724133'],
  ['toon-hair-auburn', 'Cheveux auburn', 'style', 'toon-head', 45, 'Couleur auburn', '🟠', 'hairColor', 'a55728'],
  ['toon-hair-golden', 'Cheveux dorés', 'style', 'toon-head', 70, 'Couleur dorée', '✨', 'hairColor', 'b58143'],
  ['toon-skin-deep', 'Peau brune', 'style', 'toon-head', 20, 'Teinte de peau', '🤎', 'skinColor', '5c3829'],
  ['toon-skin-light', 'Peau claire', 'style', 'toon-head', 20, 'Teinte de peau', '🤍', 'skinColor', 'f1c3a5'],
  ['toon-skin-medium', 'Peau mate', 'style', 'toon-head', 20, 'Teinte de peau', '🧡', 'skinColor', 'a36b4f'],
  ['toon-skin-tan', 'Peau dorée', 'style', 'toon-head', 20, 'Teinte de peau', '🧡', 'skinColor', 'c68e7a'],
  ['toon-skin-warm', 'Peau chaude', 'style', 'toon-head', 20, 'Teinte de peau', '🤎', 'skinColor', 'b98e6a'],
  ['toon-stroke-black', 'Contour noir', 'style', 'toon-head', 25, 'Contour noir', '⚫', 'strokeColor', '000000'],
  ['toon-stroke-pink', 'Contour rose', 'style', 'toon-head', 60, 'Contour rose', '🩷', 'strokeColor', 'ff8aab'],
  ['toon-stroke-gold', 'Contour doré', 'style', 'toon-head', 100, 'Contour doré', '✨', 'strokeColor', 'ffbe47'],
  ['toon-stroke-green', 'Contour vert', 'style', 'toon-head', 60, 'Contour vert', '🟢', 'strokeColor', '5bc971']
];

export function catalogRows() {
  return AVATAR_CATALOG.map(([slug, name, category, style, price, description, icon, optionKey = '', optionValue = '']) => ({ slug, name, category, style, price, description, icon, optionKey, optionValue }));
}
