import 'dotenv/config';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { Server } from 'socket.io';
import { initDatabase } from './database.js';
import { seedAvatarCatalog } from './avatar-seed.js';
import { authRouter } from './routes/auth.js';
import { quizRouter } from './routes/quizzes.js';
import { classRouter } from './routes/classes.js';
import { gameRouter } from './routes/games.js';
import { assignmentRouter } from './routes/assignments.js';
import { avatarRouter } from './routes/avatars.js';
import { teacherAdminRouter } from './routes/teacher-admin.js';
import { registerRealtime } from './realtime.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
const httpServer=http.createServer(app);
const allowedOrigin=process.env.APP_ORIGIN||'http://localhost:3000';
const io=new Server(httpServer,{cors:{origin:allowedOrigin,credentials:false}});
initDatabase();
const {db}=await import('./database.js');
seedAvatarCatalog(db);
app.disable('x-powered-by');
app.set('trust proxy',process.env.TRUST_PROXY==='1'?1:false);
app.use(helmet({contentSecurityPolicy:false,referrerPolicy:{policy:'strict-origin-when-cross-origin'},crossOriginResourcePolicy:{policy:'same-origin'}}));
app.use(express.json({limit:'256kb',strict:true}));
app.use(express.urlencoded({extended:false,limit:'32kb'}));
app.use('/api',rateLimit({windowMs:60_000,limit:120,standardHeaders:true,legacyHeaders:false}));
app.use('/api/auth',authRouter);
app.use('/api/quizzes',quizRouter);
app.use('/api/classes',classRouter);
app.use('/api/games',gameRouter);
app.use('/api/assignments',assignmentRouter);
app.use('/api/avatars',avatarRouter);
app.use('/api/teacher-admin',teacherAdminRouter);
app.get('/api/health',(_req,res)=>res.json({ok:true,name:'Karhoot API',version:'1.3.1',realtime:true,avatars:'toon-head'}));
app.use(express.static(path.join(__dirname,'..','public'),{dotfiles:'deny',etag:true,maxAge:'1h',index:'index.html'}));
app.use('/api',(req,res)=>res.status(404).json({error:'Route API introuvable'}));
app.use((_req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
registerRealtime(io);
const port=Number(process.env.PORT||3000);
if(!Number.isInteger(port)||port<1||port>65535)throw new Error('PORT invalide');
httpServer.listen(port,()=>console.log(`\n🎮 Karhoot running on http://localhost:${port}\n`));
